name: java-build

on:
  push:
    paths:
      - 'java/**'
      - '.github/workflows/maven.yml'
    branches:
      - master
      - release-*

  # Run build for any PR
  pull_request:
    paths:
      - 'java/**'
      - '.github/workflows/maven.yml'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.8' ]

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: build with Maven
      working-directory: java
      run: mvn package javadoc:jar source:jar --batch-mode --errors --quiet -DcreateJavadoc=true --file pom.xml --settings .maven.settings.xml
